import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Doctor Visit Summary Generator | HealthMatchAI",
  description:
    "Generate a structured summary of your symptoms, timeline, and health background to bring to your next doctor appointment. Make every visit more productive.",
  openGraph: {
    title: "Doctor Visit Summary Generator | HealthMatchAI",
    description:
      "Turn scattered symptoms and notes into a clear, doctor-ready summary that helps your clinician understand your situation faster.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Doctor Visit Summary Generator | HealthMatchAI",
    description:
      "Turn scattered symptoms and notes into a clear, doctor-ready summary that helps your clinician understand your situation faster.",
  },
};

export default function DoctorVisitSummaryPage() {
  return (
    <section className="app-page landing-page">

      {/* Hero */}
      <div className="hero-section">
        <h1>Doctor Visit Summary Generator</h1>
        <p>
          Walk into your next medical appointment with a clear, organized summary of your symptoms,
          history, and concerns so your doctor can focus on you faster.
        </p>
      </div>

      {/* Disclaimer */}
      <div className="panel disclaimer-box" style={{ marginTop: 24 }}>
        <strong>Educational purposes only.</strong> The summaries generated by HealthMatchAI are
        informational tools to support communication between you and your clinician. They are not
        medical records, diagnosis, or treatment plans. Always consult a licensed healthcare
        professional for medical decisions.
        <br />
        <strong style={{ color: "var(--danger)" }}>
          If you are experiencing a medical emergency, call 911 (US) or your local emergency
          services immediately.
        </strong>
      </div>

      {/* What Is a Doctor Visit Summary */}
      <div className="content-section" style={{ marginTop: 48 }}>
        <h2>What Is a Doctor Visit Summary?</h2>
        <p>
          A doctor visit summary is a concise, structured document that captures what you are
          experiencing before you walk into an appointment. Instead of trying to remember every
          detail on the spot while sitting in the exam room, you arrive with a written overview that
          your clinician can review quickly.
        </p>
        <p>
          HealthMatchAI generates this summary automatically from the information you provide during
          a symptom check. It organizes your primary symptom, associated symptoms, how long
          everything has been going on, your pain level, what makes things better or worse, any
          red-flag signs, and relevant health background such as medications, allergies, and chronic
          conditions.
        </p>
      </div>

      {/* Why a Summary Matters */}
      <div className="content-section" style={{ marginTop: 48 }}>
        <h2>Why a Written Summary Makes a Difference</h2>
        <p>
          Studies show that patients often forget to mention important details during appointments.
          When you are nervous, in pain, or pressed for time, it is easy to leave out a key symptom
          or omit a relevant piece of history that could change the clinical picture.
        </p>
        <p>A doctor-ready summary helps in several specific ways:</p>
        <ul>
          <li>
            <strong>Saves time during the appointment.</strong> Your clinician can read the summary
            in under a minute and jump directly into focused questions instead of starting from
            scratch.
          </li>
          <li>
            <strong>Reduces communication gaps.</strong> Written information is less likely to be
            misunderstood than a rushed verbal description.
          </li>
          <li>
            <strong>Keeps you on track.</strong> If you tend to get sidetracked or forgetful during
            appointments, the summary acts as an anchor you can refer back to.
          </li>
          <li>
            <strong>Supports telehealth visits.</strong> When you are on a video call, sharing a
            written summary in advance gives the provider context before they even see your face.
          </li>
          <li>
            <strong>Creates a personal health record.</strong> You can keep past summaries to track
            how symptoms change over time.
          </li>
        </ul>
      </div>

      {/* What the Summary Includes */}
      <div className="content-section" style={{ marginTop: 48 }}>
        <h2>What HealthMatchAI&apos;s Summary Includes</h2>
        <p>Each summary generated by HealthMatchAI contains these sections:</p>
        <ul>
          <li>
            <strong>Primary concern.</strong> The main symptom or issue that prompted you to seek
            care, stated in clear, descriptive language.
          </li>
          <li>
            <strong>Associated symptoms.</strong> Any additional symptoms you are experiencing,
            listed individually so your clinician sees the full picture.
          </li>
          <li>
            <strong>Symptom timeline.</strong> How long each symptom has lasted and whether it is
            improving, staying the same, or getting worse.
          </li>
          <li>
            <strong>Severity and impact.</strong> Your pain level, functional limitations (such as
            trouble sleeping or eating), and any notable changes in daily activity.
          </li>
          <li>
            <strong>Red-flag indicators.</strong> A clear section noting whether you flagged any
            serious warning signs like shortness of breath, chest pain, altered consciousness, or
            severe bleeding.
          </li>
          <li>
            <strong>Health background.</strong> Age, chronic conditions, current medications,
            allergies, and pregnancy status where applicable.
          </li>
          <li>
            <strong>Risk-level indication.</strong> A general guidance level (Low, Moderate, High,
            or Emergency/Crisis) based on the information you provided.
          </li>
        </ul>
      </div>

      {/* How to Use It */}
      <div className="content-section" style={{ marginTop: 48 }}>
        <h2>How to Use the Summary at Your Appointment</h2>
        <p>You can use your HealthMatchAI summary in several practical ways:</p>
        <ul>
          <li>
            <strong>Print it</strong> and hand it to the front-desk staff or nurse when you check
            in.
          </li>
          <li>
            <strong>Show it on your phone</strong> to your doctor or nurse practitioner during the
            visit.
          </li>
          <li>
            <strong>Email or message it</strong> through your patient portal before a telehealth
            appointment so the provider can review it in advance.
          </li>
          <li>
            <strong>Keep a copy</strong> for your own records so you can compare symptoms across
            multiple visits and notice patterns over time.
          </li>
        </ul>
        <p>
          The summary is not a substitute for your verbal description of symptoms. Always answer
          your clinician&apos;s questions fully and honestly. Think of the summary as a starting
          point for a more efficient conversation, not the whole conversation.
        </p>
      </div>

      {/* FAQ */}
      <div className="faq-section" style={{ marginTop: 48 }}>
        <h2>Frequently Asked Questions</h2>
        <div className="faq-list">
          <details>
            <summary>Does the summary count as an official medical record?</summary>
            <p>
              No. The HealthMatchAI summary is a personal communication tool, not a legal medical
              record. Your doctor maintains the official record of your visit. The summary simply
              helps you communicate your experience more clearly.
            </p>
          </details>
          <details>
            <summary>Will my doctor accept a printed summary from me?</summary>
            <p>
              Most clinicians appreciate when patients come prepared with organized information. A
              clear, concise summary can help the appointment start on the right foot. If you are
              unsure, ask the office staff when you check in.
            </p>
          </details>
          <details>
            <summary>Can I update the summary after I generate it?</summary>
            <p>
              You can run a new symptom check with updated information to generate a fresh summary
              at any time. HealthMatchAI also saves your previous checks so you can review them in
              your history.
            </p>
          </details>
          <details>
            <summary>Is the summary suitable for a telehealth appointment?</summary>
            <p>
              Yes. The summary is especially useful for telehealth visits where the provider cannot
              physically examine you. Sharing it through your patient portal or messaging system
              before the call gives your provider helpful context.
            </p>
          </details>
          <details>
            <summary>Does the summary include a diagnosis or prescription?</summary>
            <p>
              No. HealthMatchAI does not diagnose conditions, prescribe medication, or recommend
              specific treatments. The summary organizes what you report; it does not add clinical
              conclusions.
            </p>
          </details>
        </div>
      </div>

      {/* CTA */}
      <div className="cta-section" style={{ marginTop: 48, textAlign: "center" }}>
        <h2>Create Your Doctor-Ready Summary</h2>
        <p>
          Spend a few minutes organizing your symptoms now and walk into your next appointment
          prepared and confident.
        </p>
        <a href="/symptom-check" className="btn-primary">
          Generate My Summary
        </a>
      </div>

    </section>
  );
}
